<style>
.errors {
	list-style-type: circle;
	color: red;
	font-weight: bold;
	font-size: medium;
}

.center {
	text-align: center;
}
#tp-logo{
	background-image: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)."/frontend/base/default/css/modulodepago2/logo.png";?>");
	background-repeat: no-repeat;
	height:40px;
	width:110px;
	margin: 0 0 0 14px;
}

</style>
</head>
<body>
	<div class="contentContainer main" style="width: auto">
	<div id="tp-logo"></div>
	<form method="POST" action="<?php echo Mage::helper("adminhtml")->getUrl("*/*/*")?>">
		<div class="center">
			<?php if(count($this->errors) != 0): ?>
			<div class="errors"><ul>
				<?php foreach($this->errors as $err): ?>
				<li><?php echo $err; ?></li>
				<?php endforeach; ?>
			</ul></div>
			<?php endif; ?>
			<div id="tp-content-form fieldset"><br/>
				<div class="field">
					<label for="apynTxt" class="tp-label required"><em>*</em>Usuario de TodoPago</label>
					<div class="input-box">
						<input type="text" id="apynTxt" name="user"/>
						<span class="error" id="apynTxtError"></span>
					</div>
				</div>
				<div class="field">
					<label for="emailTxt" class="tp-label required"><em>*</em>Contrse&ntilde;a</label>
					<div class="input-box">
						<input type="password" id="emailTxt" name="pass"/><br/>
						<span class="error" id="emailTxtError"></span>
					</div>
				</div>
				<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
				<div id="tp-bt-wrapper">
					<button id="MY_btnConfirmarPago" title="Ingresar" class="button"><span>Ingresar</span></button>
				</div>
			</div>	
		</div>
	</form>
	</div>
</body></html>