<style>
    .titulos{
        font-weight: bold;
    }
    #seleccion{
        font-size: large;
    }
</style>
<?php
$order_id = $this->getRequest()->get('nroop');
$vencimiento = $this->getRequest()->get('venc');
$total = $this->getRequest()->get('total');
$codebar = $this->getRequest()->get('code');
$tipo_code = $this->getRequest()->get('tipocode');
$empresa = $this->getRequest()->get('empresa');

$order = new Mage_Sales_Model_Order ();
$order->loadByIncrementId($order_id);
?>

<div id="seleccion" style="width: 75%" >
    <div class="titulos"><h2><?php echo Mage::app()->getStore()->getName(); ?><h2><hr></div>
                <div><div class="titulos">Nro de Operaci&oacute;n</div> <?php echo $order_id ?><hr></div>
                <div><div class="titulos">Total a pagar</div> $ <?php echo $total ?><hr></div>
                <div><div class="titulos">Vencimiento</div> <?php echo $vencimiento ?><hr></div>
                <div class="titulos"><h3>DATOS PERSONALES<h3><hr></div>
                            <div><div class="titulos">Nombre</div> <?php echo $order->getBillingAddress()->getFirstname() . " " . $order->getBillingAddress()->getLastname() ?><hr></div>
                            <div><div class="titulos">Podr&aacute;s pagar este cup&oacute;n en los locales de:</div> <?php echo $empresa ?><hr></div>
                            

                <img style="width: 100%; height: 100px" src="<?php echo Mage::getBaseUrl().'modulodepago2/cupon/codebar?CODE='.$tipo_code.'&BAR='.$codebar; ?>" />            
                            <br />
                            <input type="button" name="imprimir" value="Imprimir" onclick="window.print();">
