<div class="pp-buttons-container">
    <button onclick="javascript:window.open('<?php echo $this->helper("adminhtml")->getUrl("adminhtml/credential/production");?>', 'apiwizard','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=100, top=100, width=380, height=200'); return false;" class="scalable" type="button" id="<?php echo $this->getHtmlId() ?>">
        Producci&oacute;n
    </button>
    <button onclick="javascript:window.open('<?php echo $this->helper("adminhtml")->getUrl("adminhtml/credential/developers");?>', 'apiwizard','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=100, top=100, width=380, height=200'); return false;" class="scalable" type="button" id="<?php echo $this->getSandboxHtmlId() ?>">
        Developers
    </button>
</div>